require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable

# Style cops
Style/Documentation:
  Enabled: false

# Metrics cops
Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
