version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
  redis:
    image: redis:7
    ports:
      - '6379:6379'

volumes:
  db:
