// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: server/tunnelService/tunnelService.proto

package tunnelService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelKind int32

const (
	TunnelKind_HTTP_TUNNEL TunnelKind = 0
	TunnelKind_TCP_TUNNEL  TunnelKind = 1
)

// Enum value maps for TunnelKind.
var (
	TunnelKind_name = map[int32]string{
		0: "HTTP_TUNNEL",
		1: "TCP_TUNNEL",
	}
	TunnelKind_value = map[string]int32{
		"HTTP_TUNNEL": 0,
		"TCP_TUNNEL":  1,
	}
)

func (x TunnelKind) Enum() *TunnelKind {
	p := new(TunnelKind)
	*p = x
	return p
}

func (x TunnelKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelKind) Descriptor() protoreflect.EnumDescriptor {
	return file_server_tunnelService_tunnelService_proto_enumTypes[0].Descriptor()
}

func (TunnelKind) Type() protoreflect.EnumType {
	return &file_server_tunnelService_tunnelService_proto_enumTypes[0]
}

func (x TunnelKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelKind.Descriptor instead.
func (TunnelKind) EnumDescriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{0}
}

type NewClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewClientRequest) Reset() {
	*x = NewClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tunnelService_tunnelService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewClientRequest) ProtoMessage() {}

func (x *NewClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tunnelService_tunnelService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewClientRequest.ProtoReflect.Descriptor instead.
func (*NewClientRequest) Descriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{0}
}

type NewClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (x *NewClientReply) Reset() {
	*x = NewClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tunnelService_tunnelService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewClientReply) ProtoMessage() {}

func (x *NewClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tunnelService_tunnelService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewClientReply.ProtoReflect.Descriptor instead.
func (*NewClientReply) Descriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{1}
}

func (x *NewClientReply) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type AliveMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientUUID string `protobuf:"bytes,1,opt,name=ClientUUID,proto3" json:"ClientUUID,omitempty"`
}

func (x *AliveMessage) Reset() {
	*x = AliveMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tunnelService_tunnelService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveMessage) ProtoMessage() {}

func (x *AliveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_tunnelService_tunnelService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveMessage.ProtoReflect.Descriptor instead.
func (*AliveMessage) Descriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{2}
}

func (x *AliveMessage) GetClientUUID() string {
	if x != nil {
		return x.ClientUUID
	}
	return ""
}

type AliveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AliveReply) Reset() {
	*x = AliveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tunnelService_tunnelService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveReply) ProtoMessage() {}

func (x *AliveReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tunnelService_tunnelService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveReply.ProtoReflect.Descriptor instead.
func (*AliveReply) Descriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{3}
}

type NewTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientUUID string     `protobuf:"bytes,1,opt,name=ClientUUID,proto3" json:"ClientUUID,omitempty"`
	Kind       TunnelKind `protobuf:"varint,2,opt,name=Kind,proto3,enum=tunnelService.TunnelKind" json:"Kind,omitempty"`
}

func (x *NewTunnelRequest) Reset() {
	*x = NewTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tunnelService_tunnelService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTunnelRequest) ProtoMessage() {}

func (x *NewTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tunnelService_tunnelService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTunnelRequest.ProtoReflect.Descriptor instead.
func (*NewTunnelRequest) Descriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{4}
}

func (x *NewTunnelRequest) GetClientUUID() string {
	if x != nil {
		return x.ClientUUID
	}
	return ""
}

func (x *NewTunnelRequest) GetKind() TunnelKind {
	if x != nil {
		return x.Kind
	}
	return TunnelKind_HTTP_TUNNEL
}

type NewTunnelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *NewTunnelReply) Reset() {
	*x = NewTunnelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tunnelService_tunnelService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTunnelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTunnelReply) ProtoMessage() {}

func (x *NewTunnelReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tunnelService_tunnelService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTunnelReply.ProtoReflect.Descriptor instead.
func (*NewTunnelReply) Descriptor() ([]byte, []int) {
	return file_server_tunnelService_tunnelService_proto_rawDescGZIP(), []int{5}
}

func (x *NewTunnelReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_server_tunnelService_tunnelService_proto protoreflect.FileDescriptor

var file_server_tunnelService_tunnelService_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4e, 0x65, 0x77,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a,
	0x0e, 0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x0c, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x55, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55,
	0x55, 0x49, 0x44, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x61, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x2d, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x2a, 0x2d, 0x0a, 0x0a, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0f,
	0x0a, 0x0b, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x54, 0x43, 0x50, 0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x01, 0x32,
	0xf0, 0x01, 0x0a, 0x0d, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4d, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1f,
	0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e,
	0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x1b, 0x2e, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x1f, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x72, 0x6d, 0x61, 0x6e, 0x64, 0x6d, 0x67, 0x74, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_tunnelService_tunnelService_proto_rawDescOnce sync.Once
	file_server_tunnelService_tunnelService_proto_rawDescData = file_server_tunnelService_tunnelService_proto_rawDesc
)

func file_server_tunnelService_tunnelService_proto_rawDescGZIP() []byte {
	file_server_tunnelService_tunnelService_proto_rawDescOnce.Do(func() {
		file_server_tunnelService_tunnelService_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_tunnelService_tunnelService_proto_rawDescData)
	})
	return file_server_tunnelService_tunnelService_proto_rawDescData
}

var file_server_tunnelService_tunnelService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_tunnelService_tunnelService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_tunnelService_tunnelService_proto_goTypes = []interface{}{
	(TunnelKind)(0),          // 0: tunnelService.TunnelKind
	(*NewClientRequest)(nil), // 1: tunnelService.NewClientRequest
	(*NewClientReply)(nil),   // 2: tunnelService.NewClientReply
	(*AliveMessage)(nil),     // 3: tunnelService.AliveMessage
	(*AliveReply)(nil),       // 4: tunnelService.AliveReply
	(*NewTunnelRequest)(nil), // 5: tunnelService.NewTunnelRequest
	(*NewTunnelReply)(nil),   // 6: tunnelService.NewTunnelReply
}
var file_server_tunnelService_tunnelService_proto_depIdxs = []int32{
	0, // 0: tunnelService.NewTunnelRequest.Kind:type_name -> tunnelService.TunnelKind
	1, // 1: tunnelService.TunnelService.NewClient:input_type -> tunnelService.NewClientRequest
	3, // 2: tunnelService.TunnelService.Alive:input_type -> tunnelService.AliveMessage
	5, // 3: tunnelService.TunnelService.NewTunnel:input_type -> tunnelService.NewTunnelRequest
	2, // 4: tunnelService.TunnelService.NewClient:output_type -> tunnelService.NewClientReply
	4, // 5: tunnelService.TunnelService.Alive:output_type -> tunnelService.AliveReply
	6, // 6: tunnelService.TunnelService.NewTunnel:output_type -> tunnelService.NewTunnelReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_tunnelService_tunnelService_proto_init() }
func file_server_tunnelService_tunnelService_proto_init() {
	if File_server_tunnelService_tunnelService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_tunnelService_tunnelService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tunnelService_tunnelService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tunnelService_tunnelService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliveMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tunnelService_tunnelService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tunnelService_tunnelService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tunnelService_tunnelService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTunnelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_tunnelService_tunnelService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_tunnelService_tunnelService_proto_goTypes,
		DependencyIndexes: file_server_tunnelService_tunnelService_proto_depIdxs,
		EnumInfos:         file_server_tunnelService_tunnelService_proto_enumTypes,
		MessageInfos:      file_server_tunnelService_tunnelService_proto_msgTypes,
	}.Build()
	File_server_tunnelService_tunnelService_proto = out.File
	file_server_tunnelService_tunnelService_proto_rawDesc = nil
	file_server_tunnelService_tunnelService_proto_goTypes = nil
	file_server_tunnelService_tunnelService_proto_depIdxs = nil
}
