GET http://localhost:8080/connections
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/connections
Content-Type: application/json
Accept: application/json

{
  "subdomain": "test",
  "proxied_port": "3000"
}

###

DELETE http://localhost:8080/connections/92800fa9-b465-4cb0-8c9b-92587447ee10
Content-Type: application/json
Accept: application/json
