GET http://proxy.armandmgt.me:8080/connections
Content-Type: application/json
Accept: application/json

###

POST http://proxy.armandmgt.me:8080/connections
Content-Type: application/json
Accept: application/json

{
  "subdomain": "test",
  "proxied_port": "3000"
}

###

DELETE http://proxy.armandmgt.me:8080/connections/f810c5a7-4b14-4561-88c5-20494a45bcae
Content-Type: application/json
Accept: application/json
